/******************************************************************************

Copyright (c) 2016-2019 VMware, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

******************************************************************************/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VMACCEL_MGR_H_RPCGEN
#define _VMACCEL_MGR_H_RPCGEN

#include <rpc/rpc.h>

#include "vmaccel_defs.h"
#include "vmaccel_rpc.h"

#define VMACCELMGR 0x20000078
#define VMACCELMGR_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define VMACCELMGR_REGISTER 1
VMAccelAllocateReturnStatus *vmaccelmgr_register_1(VMAccelRegisterDesc *,
                                                   CLIENT *);
VMAccelAllocateReturnStatus *vmaccelmgr_register_1_svc(VMAccelRegisterDesc *,
                                                       struct svc_req *);
#define VMACCELMGR_UNREGISTER 2
VMAccelReturnStatus *vmaccelmgr_unregister_1(VMAccelId *, CLIENT *);
VMAccelReturnStatus *vmaccelmgr_unregister_1_svc(VMAccelId *, struct svc_req *);
#define VMACCELMGR_ALLOC 3
VMAccelAllocateReturnStatus *vmaccelmgr_alloc_1(VMAccelDesc *, CLIENT *);
VMAccelAllocateReturnStatus *vmaccelmgr_alloc_1_svc(VMAccelDesc *,
                                                    struct svc_req *);
#define VMACCELMGR_FREE 4
VMAccelReturnStatus *vmaccelmgr_free_1(VMAccelId *, CLIENT *);
VMAccelReturnStatus *vmaccelmgr_free_1_svc(VMAccelId *, struct svc_req *);
int vmaccelmgr_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define VMACCELMGR_REGISTER 1
VMAccelAllocateReturnStatus *vmaccelmgr_register_1();
VMAccelAllocateReturnStatus *vmaccelmgr_register_1_svc();
#define VMACCELMGR_UNREGISTER 2
VMAccelReturnStatus *vmaccelmgr_unregister_1();
VMAccelReturnStatus *vmaccelmgr_unregister_1_svc();
#define VMACCELMGR_ALLOC 3
VMAccelAllocateReturnStatus *vmaccelmgr_alloc_1();
VMAccelAllocateReturnStatus *vmaccelmgr_alloc_1_svc();
#define VMACCELMGR_FREE 4
VMAccelReturnStatus *vmaccelmgr_free_1();
VMAccelReturnStatus *vmaccelmgr_free_1_svc();
int vmaccelmgr_1_freeresult();
#endif /* K&R C */

#endif /* !_VMACCEL_MGR_H_RPCGEN */
