/******************************************************************************

Copyright (c) 2019 VMware, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

******************************************************************************/

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vmcodec_rpc.h"

VMCODECContextAllocateReturnStatus *
vmcodec_contextalloc_1_svc(VMCODECContextAllocateDesc *argp,
                           struct svc_req *rqstp) {
   static VMCODECContextAllocateReturnStatus result;

   /*
    * insert server code here
    */

   return &result;
}

VMAccelReturnStatus *vmcodec_contextdestroy_1_svc(VMCODECContextId *argp,
                                                  struct svc_req *rqstp) {
   static VMAccelReturnStatus result;

   /*
    * insert server code here
    */

   return &result;
}

VMAccelSurfaceAllocateReturnStatus *
vmcodec_surfacealloc_1_svc(VMCODECSurfaceAllocateDesc *argp,
                           struct svc_req *rqstp) {
   static VMAccelSurfaceAllocateReturnStatus result;

   /*
    * insert server code here
    */

   return &result;
}

VMAccelReturnStatus *vmcodec_surfacedestroy_1_svc(VMCODECSurfaceId *argp,
                                                  struct svc_req *rqstp) {
   static VMAccelReturnStatus result;

   /*
    * insert server code here
    */

   return &result;
}

VMAccelReturnStatus *vmcodec_imageupload_1_svc(VMCODECImageUploadOp *argp,
                                               struct svc_req *rqstp) {
   static VMAccelReturnStatus result;

   /*
    * insert server code here
    */

   return &result;
}

VMAccelDownloadReturnStatus *
vmcodec_imagedownload_1_svc(VMCODECImageDownloadOp *argp,
                            struct svc_req *rqstp) {
   static VMAccelDownloadReturnStatus result;

   /*
    * insert server code here
    */

   return &result;
}

VMAccelReturnStatus *vmcodec_decode_1_svc(VMCODECDecodeOp *argp,
                                          struct svc_req *rqstp) {
   static VMAccelReturnStatus result;

   /*
    * insert server code here
    */

   return &result;
}

VMAccelReturnStatus *vmcodec_encode_1_svc(VMCODECEncodeOp *argp,
                                          struct svc_req *rqstp) {
   static VMAccelReturnStatus result;

   /*
    * insert server code here
    */

   return &result;
}
