/******************************************************************************

Copyright (c) 2019 VMware, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

******************************************************************************/

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "vmaccel_mgr.h"
#include "vmcodec_ops.h"
#include "vmcodec_rpc.h"
#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <ifaddrs.h>
#include <netdb.h>
#include <syslog.h>

#include "vmaccel_types_address.h"
#include "vmaccel_mgr_utils.h"
#include "log_level.h"

#ifndef SIG_PF
#define SIG_PF void (*)(int)
#endif

static void vmcodec_1(struct svc_req *rqstp, register SVCXPRT *transp) {
   union {
      VMCODECContextAllocateDesc vmcodec_contextalloc_1_arg;
      VMCODECContextId vmcodec_contextdestroy_1_arg;
      VMCODECSurfaceAllocateDesc vmcodec_surfacealloc_1_arg;
      VMCODECSurfaceId vmcodec_surfacedestroy_1_arg;
      VMCODECImageUploadOp vmcodec_imageupload_1_arg;
      VMCODECImageDownloadOp vmcodec_imagedownload_1_arg;
      VMCODECDecodeOp vmcodec_decode_1_arg;
      VMCODECEncodeOp vmcodec_encode_1_arg;
   } argument;
   char *result;
   xdrproc_t _xdr_argument, _xdr_result;
   char *(*local)(char *, struct svc_req *);

   switch (rqstp->rq_proc) {
      case NULLPROC:
         (void)svc_sendreply(transp, (xdrproc_t)xdr_void, (char *)NULL);
         return;

      case VMCODEC_CONTEXTALLOC:
         _xdr_argument = (xdrproc_t)xdr_VMCODECContextAllocateDesc;
         _xdr_result = (xdrproc_t)xdr_VMCODECContextAllocateReturnStatus;
         local =
            (char *(*)(char *, struct svc_req *))vmcodec_contextalloc_1_svc;
         break;

      case VMCODEC_CONTEXTDESTROY:
         _xdr_argument = (xdrproc_t)xdr_VMCODECContextId;
         _xdr_result = (xdrproc_t)xdr_VMAccelReturnStatus;
         local =
            (char *(*)(char *, struct svc_req *))vmcodec_contextdestroy_1_svc;
         break;

      case VMCODEC_SURFACEALLOC:
         _xdr_argument = (xdrproc_t)xdr_VMCODECSurfaceAllocateDesc;
         _xdr_result = (xdrproc_t)xdr_VMAccelSurfaceAllocateReturnStatus;
         local =
            (char *(*)(char *, struct svc_req *))vmcodec_surfacealloc_1_svc;
         break;

      case VMCODEC_SURFACEDESTROY:
         _xdr_argument = (xdrproc_t)xdr_VMCODECSurfaceId;
         _xdr_result = (xdrproc_t)xdr_VMAccelReturnStatus;
         local =
            (char *(*)(char *, struct svc_req *))vmcodec_surfacedestroy_1_svc;
         break;

      case VMCODEC_IMAGEUPLOAD:
         _xdr_argument = (xdrproc_t)xdr_VMCODECImageUploadOp;
         _xdr_result = (xdrproc_t)xdr_VMAccelReturnStatus;
         local = (char *(*)(char *, struct svc_req *))vmcodec_imageupload_1_svc;
         break;

      case VMCODEC_IMAGEDOWNLOAD:
         _xdr_argument = (xdrproc_t)xdr_VMCODECImageDownloadOp;
         _xdr_result = (xdrproc_t)xdr_VMAccelDownloadReturnStatus;
         local =
            (char *(*)(char *, struct svc_req *))vmcodec_imagedownload_1_svc;
         break;

      case VMCODEC_DECODE:
         _xdr_argument = (xdrproc_t)xdr_VMCODECDecodeOp;
         _xdr_result = (xdrproc_t)xdr_VMAccelReturnStatus;
         local = (char *(*)(char *, struct svc_req *))vmcodec_decode_1_svc;
         break;

      case VMCODEC_ENCODE:
         _xdr_argument = (xdrproc_t)xdr_VMCODECEncodeOp;
         _xdr_result = (xdrproc_t)xdr_VMAccelReturnStatus;
         local = (char *(*)(char *, struct svc_req *))vmcodec_encode_1_svc;
         break;

      default:
         svcerr_noproc(transp);
         return;
   }
   memset((char *)&argument, 0, sizeof(argument));
   if (!svc_getargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument)) {
      svcerr_decode(transp);
      return;
   }
   result = (*local)((char *)&argument, rqstp);
   if (result != NULL &&
       !svc_sendreply(transp, (xdrproc_t)_xdr_result, result)) {
      svcerr_systemerr(transp);
   }
   if (!svc_freeargs(transp, (xdrproc_t)_xdr_argument, (caddr_t)&argument)) {
      syslog(LOG_ERR, "%s", "unable to free arguments");
      exit(1);
   }
   return;
}

int main(int argc, char **argv) {
   register SVCXPRT *transp;
   VMAccelAllocateStatus *allocStatus;
   VMAccelMgrClient mgrClient = {NULL, NULL, -1};

   pmap_unset(VMCODEC, VMCODEC_VERSION);
   openlog("vmcodec_rpc", LOG_PID, LOG_DAEMON);

   transp = svcudp_create(RPC_ANYSOCK);
   if (transp == NULL) {
      syslog(LOG_ERR, "%s", "cannot create udp service.");
      exit(1);
   }
   if (!svc_register(transp, VMCODEC, VMCODEC_VERSION, vmcodec_1,
                     IPPROTO_UDP)) {
      syslog(LOG_ERR, "%s",
             "unable to register (VMCODEC, VMCODEC_VERSION, udp).");
      exit(1);
   }

   transp = svctcp_create(RPC_ANYSOCK, 0, 0);
   if (transp == NULL) {
      syslog(LOG_ERR, "%s", "cannot create tcp service.");
      exit(1);
   }
   if (!svc_register(transp, VMCODEC, VMCODEC_VERSION, vmcodec_1,
                     IPPROTO_TCP)) {
      syslog(LOG_ERR, "%s",
             "unable to register (VMCODEC, VMCODEC_VERSION, tcp).");
      exit(1);
   }

   allocStatus = vmcodec_poweron_svc(NULL);

   if ((allocStatus == NULL) || (allocStatus->status != VMACCEL_SUCCESS)) {
      Warning("Failed to power on VMCODEC...\n");
      exit(1);
   }

   /*
    * Managment host specified.
    */
   if (argc >= 3) {
      char *iface = argv[1];
      char *host = argv[2];

      mgrClient = vmaccelmgr_register(host, iface, &allocStatus->desc);

      if (mgrClient.clnt == NULL) {
         Warning("Unable to register with management server...\n");
         vmcodec_poweroff_svc();
         exit(1);
      }
   }

   svc_run();
   syslog(LOG_ERR, "%s", "svc_run returned");

   if (mgrClient.clnt != NULL) {
      vmaccelmgr_unregister(&mgrClient);
   }

   vmcodec_poweroff_svc();
   exit(1);
   /* NOTREACHED */
}
