/******************************************************************************

Copyright (c) 2019 VMware, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    1. Redistributions of source code must retain the above copyright notice,
       this list of conditions and the following disclaimer.

    2. Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

******************************************************************************/

/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "vmcodec_rpc.h"


static void vmcodec_1(char *host) {
   CLIENT *clnt;
   VMCODECContextAllocateReturnStatus *result_1;
   VMCODECContextAllocateDesc vmcodec_contextalloc_1_arg;
   VMAccelReturnStatus *result_2;
   VMCODECContextId vmcodec_contextdestroy_1_arg;
   VMAccelSurfaceAllocateReturnStatus *result_3;
   VMCODECSurfaceAllocateDesc vmcodec_surfacealloc_1_arg;
   VMAccelReturnStatus *result_4;
   VMCODECSurfaceId vmcodec_surfacedestroy_1_arg;
   VMAccelReturnStatus *result_5;
   VMCODECImageUploadOp vmcodec_imageupload_1_arg;
   VMAccelDownloadReturnStatus *result_6;
   VMCODECImageDownloadOp vmcodec_imagedownload_1_arg;
   VMAccelReturnStatus *result_7;
   VMCODECDecodeOp vmcodec_decode_1_arg;
   VMAccelReturnStatus *result_8;
   VMCODECEncodeOp vmcodec_encode_1_arg;

#ifndef DEBUG
   clnt = clnt_create(host, VMCODEC, VMCODEC_VERSION, "udp");
   if (clnt == NULL) {
      clnt_pcreateerror(host);
      exit(1);
   }
#endif /* DEBUG */

   result_1 = vmcodec_contextalloc_1(&vmcodec_contextalloc_1_arg, clnt);
   if (result_1 == (VMCODECContextAllocateReturnStatus *)NULL) {
      clnt_perror(clnt, "call failed");
   }
   result_2 = vmcodec_contextdestroy_1(&vmcodec_contextdestroy_1_arg, clnt);
   if (result_2 == (VMAccelReturnStatus *)NULL) {
      clnt_perror(clnt, "call failed");
   }
   result_3 = vmcodec_surfacealloc_1(&vmcodec_surfacealloc_1_arg, clnt);
   if (result_3 == (VMAccelSurfaceAllocateReturnStatus *)NULL) {
      clnt_perror(clnt, "call failed");
   }
   result_4 = vmcodec_surfacedestroy_1(&vmcodec_surfacedestroy_1_arg, clnt);
   if (result_4 == (VMAccelReturnStatus *)NULL) {
      clnt_perror(clnt, "call failed");
   }
   result_5 = vmcodec_imageupload_1(&vmcodec_imageupload_1_arg, clnt);
   if (result_5 == (VMAccelReturnStatus *)NULL) {
      clnt_perror(clnt, "call failed");
   }
   result_6 = vmcodec_imagedownload_1(&vmcodec_imagedownload_1_arg, clnt);
   if (result_6 == (VMAccelDownloadReturnStatus *)NULL) {
      clnt_perror(clnt, "call failed");
   }
   result_7 = vmcodec_decode_1(&vmcodec_decode_1_arg, clnt);
   if (result_7 == (VMAccelReturnStatus *)NULL) {
      clnt_perror(clnt, "call failed");
   }
   result_8 = vmcodec_encode_1(&vmcodec_encode_1_arg, clnt);
   if (result_8 == (VMAccelReturnStatus *)NULL) {
      clnt_perror(clnt, "call failed");
   }
#ifndef DEBUG
   clnt_destroy(clnt);
#endif /* DEBUG */
}


int main(int argc, char *argv[]) {
   char *host;

   if (argc < 2) {
      printf("usage: %s server_host\n", argv[0]);
      exit(1);
   }
   host = argv[1];
   vmcodec_1(host);
   exit(0);
}
